name: Create Azure resources
on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      - name: Verify Secrets
        run: echo ${{ secrets.AZURE_CREDENTIALS }}

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Verify Azure CLI
      - name: Verify Azure CLI
        run: |
          az account show
          az account list -o table

      # Deploy Bicep file
      - name: Create Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ${{ github.workspace }}/config/main.bicep
          parameters: "namePrefix=${{ vars.AZURE_PREFIX }}"
          failOnStdErr: false

      # Output deployment results
      - name: Output Deployment Results
        run: |
          echo "Deployment completed. Resource group: ${{ vars.AZURE_RG }}"
          az group list -o table