name: Create Azure resources
on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Verify AZURE_CREDENTIALS structure
      - name: Verify AZURE_CREDENTIALS structure
        run: |
          echo "Verifying AZURE_CREDENTIALS structure..."
          CREDS='${{ secrets.AZURE_CREDENTIALS }}'
          if [ -z "$CREDS" ]; then
            echo "Error: AZURE_CREDENTIALS is empty"
            exit 1
          fi
          
          if ! echo "$CREDS" | jq -e '.clientId and .clientSecret and .subscriptionId and .tenantId' > /dev/null; then
            echo "Error: AZURE_CREDENTIALS is missing required fields"
            echo "Fields present: $(echo "$CREDS" | jq 'keys')"
            exit 1
          fi
          echo "AZURE_CREDENTIALS structure is correct"
          
          echo "Verifying field lengths..."
          CLIENT_ID=$(echo "$CREDS" | jq -r '.clientId')
          TENANT_ID=$(echo "$CREDS" | jq -r '.tenantId')
          SUBSCRIPTION_ID=$(echo "$CREDS" | jq -r '.subscriptionId')
          
          echo "Client ID length: ${#CLIENT_ID}"
          echo "Tenant ID length: ${#TENANT_ID}"
          echo "Subscription ID length: ${#SUBSCRIPTION_ID}"
          
          if [ ${#CLIENT_ID} -lt 10 ] || [ ${#TENANT_ID} -lt 10 ] || [ ${#SUBSCRIPTION_ID} -lt 10 ]; then
            echo "Error: One or more fields in AZURE_CREDENTIALS seem too short"
            exit 1
          fi
          echo "Field lengths seem reasonable"

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Verify Azure CLI
      - name: Verify Azure CLI
        run: |
          az account show
          az account list -o table

      # Deploy Bicep file
      - name: Create Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ${{ github.workspace }}/config/main.bicep
          parameters: "namePrefix=${{ vars.AZURE_PREFIX }}"
          failOnStdErr: false

      # Output deployment results
      - name: Output Deployment Results
        run: |
          echo "Deployment completed. Resource group: ${{ vars.AZURE_RG }}"
          az group list -o table