name: Test Secret Access
on: [workflow_dispatch]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for TEST_SECRET
        run: |
          if [ -n "${{ secrets.TEST_SECRET }}" ]; then
            echo "TEST_SECRET is accessible"
          else
            echo "TEST_SECRET is not accessible"
          fi
      
      - name: Check for AZURE_CREDENTIALS
        run: |
          if [ -n "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "AZURE_CREDENTIALS is accessible"
            echo "Length of AZURE_CREDENTIALS: ${#{{ secrets.AZURE_CREDENTIALS }}}"
          else
            echo "AZURE_CREDENTIALS is not accessible"
          fi